id: ID78D3E0B
ocr_import_info:
  bdrc_scan_id: W1KG8900
  source: bdrc
  ocr_info:
    timestamp: '2022-08-25T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-01-21 16:31:14.589963
last_modified: 2022-08-25 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG8900
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG8900
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས། ༼རྫོང་སར་ཁམས་བྱེའི་གློག་ཀླད་པར་མ།༽
  languages:
  - bo
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
bases:
  I1KG8989:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8989
      total_pages: 602
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG8989.txt
    order: 1
  I1KG8991:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8991
      total_pages: 722
      volume_number: 3
      volume_pages_bdrc_intro: 2
    base_file: I1KG8991.txt
    order: 2
  I1KG8990:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8990
      total_pages: 604
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I1KG8990.txt
    order: 3
  I1KG8992:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8992
      total_pages: 672
      volume_number: 4
      volume_pages_bdrc_intro: 2
    base_file: I1KG8992.txt
    order: 4
  I1KG8993:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8993
      total_pages: 566
      volume_number: 5
      volume_pages_bdrc_intro: 2
    base_file: I1KG8993.txt
    order: 5
  I1KG8994:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8994
      total_pages: 660
      volume_number: 6
      volume_pages_bdrc_intro: 2
    base_file: I1KG8994.txt
    order: 6
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
